# Generated by Django 5.2.8 on 2025-12-03 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_ultima_compra', models.DateTimeField(auto_now=True)),
                ('total_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frecuencia_visitas', models.IntegerField(default=0)),
                ('cluster_ia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo_base', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.FloatField()),
                ('elasticidad_precio', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dia_semana', models.IntegerField(blank=True, null=True)),
                ('es_hora_pico', models.BooleanField(default=False)),
                ('clima', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prediccion.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prediccion.producto')),
            ],
        ),
    ]
